In [6]:
import numpy as np
list=[0,1,2,5,6,8,10] 
n1=np.array(list)
print(n1)

type(n1)

[ 0  1  2  5  6  8 10]


numpy.ndarray

In [8]:
n2=np.array([[1,2,3,4],[5,6,7,8]])
print(n2)

[[1 2 3 4]
 [5 6 7 8]]


In [18]:
# all zero array n=np.zeros((row,col)), for one dimentional x=np.zeros(n)
n2=np.zeros((3,6))
print(n2)

# for all one array n=np.ones((row,col)) similiar for one dimentional
n3=np.ones((3,3))
print(n3)


#for other value we need to use full n=np.full((dimention),value)
n4=np.full((3,4),7)
print(n4)



[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]


In [22]:
#Initializing numpy array within a range (np.arange())
n5=np.arange(10,20)  # will generate array from 10 - 19 (not containing righter value)
print(n5)

#range and number getting incremented by certain value np.arange(left,right,inc)
n6=np.arange(10,50,5)
print(n6)

# generate array with random value np.random.randint(range,n)
n7=np.random.randint(1,20,5)    
print(n7)


[10 11 12 13 14 15 16 17 18 19]
[10 15 20 25 30 35 40 45]
[16  5  9 15 16]


In [29]:
# Checking shape and changing the shape of numpy array
n2=np.array([[1,2,3,4],[5,6,7,8]])
n2.shape  # Will show the dimention of the array

n2.shape=(4,2)  # reshape array into desired dimention(can interchange between col and row)
print(n2)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
