In [5]:
import numpy as np
l1=[1,2,3,4,5]
l2=[3,4,5,6,7]

n1=np.array(l1)
print(n1)
type(n1)

[1 2 3 4 5]


numpy.ndarray

In [7]:
n2=np.array([l1,l2])
x=np.full((2,3),2)
print(x)

[[2 2 2]
 [2 2 2]]


In [ ]:
for i in range(3):
    for j in range(2):
        x=int(input())
        l1.append(x)